import type { MessageDTO, MessageStatus, PublicUser } from "./types";

/**
 * Strongly-typed Socket.IO contracts shared by client and server.
 * Business logic lives in services; these types only describe the transport.
 */

// ---- client -> server ----
export interface ClientToServerEvents {
  "conversation:join": (
    payload: { conversationId: string },
    ack: (res: AckResult<{ ok: true }>) => void,
  ) => void;

  "conversation:leave": (payload: { conversationId: string }) => void;

  "message:send": (
    payload: SendMessagePayload,
    ack: (res: AckResult<{ message: MessageDTO }>) => void,
  ) => void;

  "message:read": (
    payload: { conversationId: string; upToSeq: number },
    ack?: (res: AckResult<{ ok: true }>) => void,
  ) => void;

  "typing:start": (payload: { conversationId: string }) => void;
  "typing:stop": (payload: { conversationId: string }) => void;

  /** Sent on (re)connect so the server can replay anything missed. */
  "sync:since": (
    payload: { conversationId: string; afterSeq: number },
    ack: (res: AckResult<{ messages: MessageDTO[] }>) => void,
  ) => void;
}

// ---- server -> client ----
export interface ServerToClientEvents {
  "message:new": (message: MessageDTO) => void;
  /** Read/delivery status changed for messages the recipient just observed. */
  "message:status": (payload: {
    conversationId: string;
    upToSeq: number;
    status: Extract<MessageStatus, "delivered" | "read">;
    byUserId: string;
  }) => void;
  "typing:update": (payload: {
    conversationId: string;
    userId: string;
    typing: boolean;
  }) => void;
  "presence:update": (payload: { userId: string; online: boolean; lastSeenAt: string }) => void;
  "conversation:bump": (payload: { conversationId: string }) => void;
  "group:updated": (payload: GroupUpdatedPayload) => void;
}

export interface GroupUpdatedPayload {
  conversationId: string;
  type: "created" | "member_added" | "member_removed" | "member_left" | "admin_changed" | "info_updated";
  targetUserId?: string;
  newAdminId?: string;
  title?: string;
}

export interface SendMessagePayload {
  conversationId: string;
  /** Idempotency key generated by the client. */
  clientId: string;
  type: "TEXT" | "IMAGE" | "GIF" | "STICKER";
  body?: string;
  /** For IMAGE: a previously-uploaded+approved attachment id. */
  attachmentId?: string;
  /** For GIF/STICKER: the external/bundled URL + dimensions. */
  media?: { url: string; width?: number; height?: number; mime?: string };
}

/** Discriminated ack result so clients can branch on success safely. */
export type AckResult<T> =
  | ({ ok: true } & T)
  | { ok: false; error: { code: string; message: string; detail?: Record<string, unknown> } };

export interface SocketData {
  userId: string;
  username: string;
}

export type { PublicUser };
